/**
 * Overused/generic phrases — single source of truth for editorial quality checks.
 *
 * These are words/phrases that weaken writing quality when overused.
 * They tend to be generic, vague, or formulaic — the opposite of the specific,
 * concrete, practitioner-level writing that Google Search Central values.
 *
 * Used by:
 *   1. SEO Audit (`article-audit.ts`) — flags them as editorial quality warnings
 *   2. Claude writer prompt (`claude/client.ts`) — encourages the model to use specific language
 *   3. E-E-A-T Python audit (`tools/content_audit/`) — scored under "lazy phrasing"
 *
 * Split into two tiers:
 *   HIGH — Strong generic markers that weaken content quality. Weighted in audit.
 *   COMMON — Can appear in normal writing but cluster badly when overused.
 */

/** Strong generic markers — overused phrases that weaken writing quality. */
export const AI_PHRASES_HIGH: readonly string[] = [
  "delve",
  "delve into",
  "landscape",
  "realm",
  "plethora",
  "myriad",
  "holistic",
  "game-changer",
  "game changer",
  "revolutionary",
  "cutting-edge",
  "cutting edge",
  "seamless",
  "seamlessly",
  "robust",
  "in today's world",
  "in today's digital landscape",
  "in today's digital age",
  "in today's competitive",
  "in today's fast-paced",
  "it's important to note",
  "it's important to note that",
  "it's worth noting",
  "in conclusion",
  "dive deep",
  "dive into",
  "harness",
  "harness the power",
  "unlock",
  "unlock the power",
  "unleash",
  "unleash the power",
  "in this article we'll",
  "let's explore",
  "unlike traditional",
  "over time, this builds",
  "a testament to",
  "plays a crucial role",
  "facilitate",
  "foster",
  "empower",
  "elevate",
  "streamline",
  "pivotal",
  "paramount",
  "endeavor",
  "look no further",
  "without further ado",
  "this comprehensive guide",
  "whether you're a",
  "as we all know",
  "it goes without saying",
  "needless to say",
  "in order to",
  "when it comes to",
  "stands as a",
  "serves as a",
  "plays a vital role",
  "it is worth mentioning",
  "at the end of the day",
  "the bottom line is",
  "rest assured",
  "it's no secret that",
  "there's no denying",
  "take your .* to the next level",
] as const;

/** Textbook opener patterns — weak paragraph starters that signal AI/academic writing.
 * These are checked as regex patterns against the first sentence of each paragraph. */
export const TEXTBOOK_OPENERS: readonly string[] = [
  "there are several",
  "there are many",
  "there are a number of",
  "there are various",
  "it is important to",
  "it is worth mentioning",
  "it is essential to",
  "it is crucial to",
  "it should be noted",
  "it can be observed",
  "one of the most",
  "one must consider",
  "one should note",
  "when it comes to",
  "in order to understand",
  "in order to achieve",
  "as mentioned earlier",
  "as previously discussed",
  "as we all know",
  "it goes without saying",
  "needless to say",
  "the importance of",
  "the purpose of this",
  "this section will",
  "this article will",
  "let us now turn to",
  "we will now discuss",
  "we will now explore",
  "in the world of",
  "in the realm of",
  "in the ever-evolving",
  "in an era of",
  "in an increasingly",
  "the landscape of",
  "the world of",
] as const;

/** Common phrases that weaken quality when clustered. Individually fine; flagged in quantity. */
export const AI_PHRASES_COMMON: readonly string[] = [
  "crucial",
  "comprehensive",
  "leverage",
  "utilize",
  "navigate",
  "when it comes to",
  "certainly,",
  "indeed,",
  "furthermore,",
  "moreover,",
  "in terms of",
  "ultimately,",
  "essentially,",
  "basically,",
  "a solid ",
  "this guide covers",
  "practical steps",
  "helps you reach",
  "aligns your",
  "builds trust over time",
  "round out",
  "when it fits",
  "where it sounds natural",
  "ensure your",
  "ensure that",
  "consider a ",
  "supports the decision",
  "worth optimizing for",
  "combined with",
  "match content to intent",
  "focus on ",
  "start with ",
] as const;

/** Suggested replacements for generic phrases. Makes editorial alerts actionable. */
export const AI_PHRASE_SUGGESTIONS: Readonly<Record<string, string>> = {
  crucial: "key, needed, or be specific",
  comprehensive: "full, complete, or describe what's covered",
  "game-changer": "concrete claim or cut",
  utilize: "use",
  "ensure your": "make sure",
  "ensure that": "make sure",
  leverage: "use or take advantage of",
  delve: "look at or explore",
  "delve into": "look at or explore",
  myriad: "many or list examples",
  plethora: "many or list examples",
  holistic: "full or whole",
  "in conclusion": "cut or end with a concrete takeaway",
  "it's important to note": "here's what matters or keep in mind",
  "it's important to note that": "here's what matters or keep in mind",
  "in today's digital landscape": "cut or use specific context",
  "in today's world": "cut or use specific context",
  revolutionary: "concrete claim or cut",
  "cutting-edge": "concrete claim or cut",
  "combined with": "plus or along with",
  "unlike traditional": "say the contrast in plain language",
  facilitate: "help or enable",
  foster: "build or encourage",
  empower: "enable or help",
  elevate: "raise or improve",
  streamline: "simplify or speed up",
  pivotal: "key or critical",
  paramount: "most important or top priority",
  endeavor: "effort or project",
  "a testament to": "shows or proves",
  "plays a crucial role": "matters or is key",
  "plays a vital role": "matters or is key",
  "look no further": "cut — just state what you recommend",
  "without further ado": "cut entirely",
  "this comprehensive guide": "cut or name what it actually covers",
  "whether you're a": "cut — address the actual reader directly",
  "as we all know": "cut or state the fact directly",
  "it goes without saying": "cut — if it goes without saying, don't say it",
  "needless to say": "cut — just say the thing",
  "in order to": "to",
  "when it comes to": "for or regarding, or just name the thing",
  "stands as a": "is",
  "serves as a": "is or works as",
  "at the end of the day": "cut or state the conclusion directly",
  "the bottom line is": "cut or lead with the point",
  "rest assured": "cut — show evidence instead",
  "it's no secret that": "cut — state the fact",
  "there's no denying": "cut — state the fact",
  "seamlessly": "smoothly or without friction, or be specific",
  "game changer": "concrete claim or cut",
  "cutting edge": "concrete claim or cut",
  "dive into": "look at or examine",
};

/**
 * Generate a comma-separated list for LLM prompts.
 * Combines high and selected common generic phrases to encourage specific language.
 */
export function getBannedPhrasesForPrompt(): string {
  // Include all high-confidence phrases and key common ones for the writer prompt
  const combined = [
    ...AI_PHRASES_HIGH,
    // Common phrases most likely to appear in AI output
    "leverage", "utilize", "comprehensive", "crucial",
    "when it comes to", "furthermore,", "moreover,",
    "consider a", "focus on", "start with",
  ];
  // Deduplicate
  return [...new Set(combined)].map((p) => `"${p}"`).join(", ");
}
