/**
 * Build-time script: discovers all page.tsx files in src/app and generates
 * a typed route manifest for the sitemap.
 *
 * Usage:
 *   npx tsx scripts/generate-sitemap-routes.ts          # generate
 *   npx tsx scripts/generate-sitemap-routes.ts --check   # verify up-to-date (CI)
 */

import { readdirSync, statSync, readFileSync, writeFileSync } from "fs";
import { join, sep } from "path";

const APP_DIR = join(process.cwd(), "src", "app");
const OUTPUT_FILE = join(process.cwd(), "src", "lib", "sitemap", "generated-routes.ts");

const EXCLUDED_PATHS = new Set([
  "/partner/dashboard",
  "/partner/login",
  "/partner/forgot-password",
  "/partner/set-password",
  "/dashboard/login",
]);

const EXCLUDED_PREFIXES = ["/dashboard", "/api"];

function walkDir(dir: string): string[] {
  const results: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      results.push(...walkDir(full));
    } else if (entry === "page.tsx" || entry === "page.ts") {
      results.push(full);
    }
  }
  return results;
}

function filePathToRoute(filePath: string): string | null {
  let route = filePath
    .replace(APP_DIR, "")
    .replace(/\/page\.tsx?$/, "")
    .split(sep)
    .join("/");

  // Strip route groups like (main)
  route = route.replace(/\/\([^)]+\)/g, "");

  // Skip dynamic routes - handled by dedicated fetchers
  if (route.includes("[")) return null;

  // Normalize root
  if (route === "") route = "/";

  // Apply exclusions
  if (EXCLUDED_PATHS.has(route)) return null;
  if (EXCLUDED_PREFIXES.some((prefix) => route.startsWith(prefix + "/") || route === prefix)) {
    return null;
  }

  return route;
}

function generateContent(routes: string[]): string {
  const lines = routes.map((r) => `  "${r}",`).join("\n");
  return `// AUTO-GENERATED by scripts/generate-sitemap-routes.ts - do not edit manually
// Run: npm run generate:sitemap-routes
export const DISCOVERED_ROUTES: string[] = [
${lines}
];
`;
}

const pages = walkDir(APP_DIR);
const routes = pages
  .map(filePathToRoute)
  .filter((r): r is string => r !== null)
  .sort((a, b) => {
    if (a === "/") return -1;
    if (b === "/") return 1;
    return a.localeCompare(b);
  });

// Remove duplicates (route groups can collapse to same path)
const uniqueRoutes = [...new Set(routes)];

const content = generateContent(uniqueRoutes);

if (process.argv.includes("--check")) {
  try {
    const existing = readFileSync(OUTPUT_FILE, "utf-8");
    if (existing === content) {
      console.log("Sitemap routes are up to date.");
      process.exit(0);
    } else {
      console.error(
        "Sitemap routes are stale. Run: npm run generate:sitemap-routes"
      );
      process.exit(1);
    }
  } catch {
    console.error(
      "Generated routes file not found. Run: npm run generate:sitemap-routes"
    );
    process.exit(1);
  }
} else {
  writeFileSync(OUTPUT_FILE, content, "utf-8");
  console.log(`Generated ${uniqueRoutes.length} routes -> ${OUTPUT_FILE}`);
}
